### ISSUE TITLE
Not compatible with your operating system or architecture

### ISSUE THREAD

**Issue by custardpy** [lmatteis/peer-tweet#4]
I got errors when trying to fire up _npm install_:
`$npm install
electron-react-boilerplate@0.7.1 postinstall /home/user/peer-tweet-master
node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
npm WARN optional Skipping failed optional dependency /fbjs-scripts/babel/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN optional Skipping failed optional dependency /webpack/watchpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7`

OS: Fedora release 23 x86_64
npm: v3.6.0
node: v5.6.0

**Comment by lmatteis** [comment]
Yikes... it seems like a problem others are having as well https://github.com/npm/npm/issues/10768

One possible fix might be to try and use Node LTS?

I will look into a possible fix after doing some research.

I might need to make the code depend on a specific version of Node/NPM to avoid these kind of problems. Ideas?

**Comment by lmatteis** [comment]
Ok I fixed this. The problem is that you need to install Python 2.7 to compile native modules: https://github.com/nodejs/node-gyp
